"""create customers table

Revision ID: c326bf97493f
Revises: 
Create Date: 2026-10-08 12:08:59.537600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c326bf97493f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senior_citizen', sa.Boolean(), nullable=False),
    sa.Column('has_partner', sa.Boolean(), nullable=False),
    sa.Column('has_dependents', sa.Boolean(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('contract', sa.String(length=20), nullable=False),
    sa.Column('paperless_billing', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('monthly_charges', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('phone_service', sa.Boolean(), nullable=False),
    sa.Column('multiple_lines', sa.String(length=25), nullable=False),
    sa.Column('internet_service', sa.String(length=20), nullable=False),
    sa.Column('online_security', sa.String(length=25), nullable=False),
    sa.Column('online_backup', sa.String(length=25), nullable=False),
    sa.Column('device_protection', sa.String(length=25), nullable=False),
    sa.Column('tech_support', sa.String(length=25), nullable=False),
    sa.Column('streaming_tv', sa.String(length=25), nullable=False),
    sa.Column('streaming_movies', sa.String(length=25), nullable=False),
    sa.Column('churned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_external_id'), 'customers', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
