"""generalize customer schema

Revision ID: ca4a1fda9c9c
Revises: c326bf97493f
Create Date: 2026-10-09 09:32:36.778291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca4a1fda9c9c'
down_revision: Union[str, Sequence[str], None] = 'c326bf97493f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('company_name', sa.String(length=160), nullable=True))
    op.add_column('customers', sa.Column('subscription_plan', sa.String(length=80), nullable=True))
    op.add_column('customers', sa.Column('monthly_revenue', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('customers', sa.Column('usage_minutes_last_30d', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('customers', sa.Column('logins_last_30d', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('active_days_last_30d', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('support_ticket_count', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('unresolved_ticket_count', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('payment_failures', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('source_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('customers', 'external_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('customers', 'full_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('customers', 'tenure_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customers', 'churned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('customers', 'online_backup')
    op.drop_column('customers', 'device_protection')
    op.drop_column('customers', 'multiple_lines')
    op.drop_column('customers', 'senior_citizen')
    op.drop_column('customers', 'contract')
    op.drop_column('customers', 'has_partner')
    op.drop_column('customers', 'tech_support')
    op.drop_column('customers', 'phone_service')
    op.drop_column('customers', 'monthly_charges')
    op.drop_column('customers', 'streaming_movies')
    op.drop_column('customers', 'streaming_tv')
    op.drop_column('customers', 'payment_method')
    op.drop_column('customers', 'online_security')
    op.drop_column('customers', 'has_dependents')
    op.drop_column('customers', 'paperless_billing')
    op.drop_column('customers', 'internet_service')
    op.drop_column('customers', 'total_charges')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('total_charges', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('internet_service', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('paperless_billing', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('has_dependents', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('online_security', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('payment_method', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('streaming_tv', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('streaming_movies', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('monthly_charges', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('phone_service', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('tech_support', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('has_partner', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('contract', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('senior_citizen', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('multiple_lines', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('device_protection', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('online_backup', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.alter_column('customers', 'churned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('customers', 'tenure_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customers', 'full_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('customers', 'external_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'source_attributes')
    op.drop_column('customers', 'last_active_at')
    op.drop_column('customers', 'payment_failures')
    op.drop_column('customers', 'unresolved_ticket_count')
    op.drop_column('customers', 'support_ticket_count')
    op.drop_column('customers', 'active_days_last_30d')
    op.drop_column('customers', 'logins_last_30d')
    op.drop_column('customers', 'usage_minutes_last_30d')
    op.drop_column('customers', 'monthly_revenue')
    op.drop_column('customers', 'subscription_plan')
    op.drop_column('customers', 'company_name')
    # ### end Alembic commands ###
